### PR TITLE
Updated Documents

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
### Minor updates with easy merging and no feature changes.

Partially fixes issue #15 
- Added punctuation marks and fixed typos in documentation.

Fixes issue #20 
- Added channel stable instead of master to avoid runtime errors while installing the app.

### CODE REVIEW

**Comment by ItsAdityaKSingh** [comment]
@Techno-Disaster You may merge this PR.

**Comment by Techno-Disaster** [comment]
IMHO we don't really need this atm, so closing. (no one really sees commas and full stops afaik). As for the flutter master or stable changes, that would require changing stuff in a lot of places including the ci and ccextractor.org which can be done sometime later in a seperate MR specifically for this.

**Comment by ItsAdityaKSingh** [comment]
But during installation of this particular repo, the installation guide causes error in master. I guess it would be well off for others if it's changed. Also I wanted to start contributing to this repository and these documentary changes were a good start I had :(

**Comment by Techno-Disaster** [comment]
> h



> But during installation of this particular repo, the installation guide causes error in master. I guess it would be well off for others if it's changed. Also I wanted to start contributing to this repository and these documentary changes were a good start I had :(

readme and ci switched to stable. https://github.com/CCExtractor/ccextractorfluttergui/commit/f49a9ab4d656d0f6c93ee0af912c7f5ef9542282

**Pull request closed without merging**
