### PR TITLE
Added Drag And Drop Support For The Desktop Application

### PR DESCRIPTION
**Pull request by manoj1749**
- This pr will be resolving the issue #6 and [CCExtractor
ccextractor/issue-1413](https://github.com/CCExtractor/ccextractor/issues/1413)
- Using desktop_drop package I had addes the drag and drop feature which works same as the AddFilesButton.

### Working Video

https://user-images.githubusercontent.com/83648898/216996162-78db7cab-9b41-4e3a-ad91-9b6a729b4d99.mp4

### CODE REVIEW

**Comment by Techno-Disaster** [comment]
Can you make the whole windows the drop target and keep the button labelled "Add files"?

**Comment by manoj1749** [comment]
> Can you make the whole windows the drop target and keep the button labelled "Add files"?

Yeah I can do that

**Comment by Techno-Disaster** [comment]
LGTM, one small change, upon hover can you change the drop area to "drop files here" or something similar?

**Comment by Techno-Disaster** [comment]
also formatting and stuff, ci fails atm

**Comment by manoj1749** [comment]
I think it was due to the flutter format command as if you check the log in line 37 it states " [!] The "format" command is deprecated and will be removed in a future version of Flutter. Please use the "dart format" sub-command instead, which takes all of the same command-line arguments as "flutter format". [37](https://github.com/CCExtractor/ccextractorfluttergui/actions/runs/4116613267/jobs/7112926049#step:4:38) "

**Comment by manoj1749** [comment]
> LGTM, one small change, upon hover can you change the drop area to "drop files here" or something similar?

ok will try to do that

**Comment by manoj1749** [comment]
Heyy, @Techno-Disaster , I've tried to do what you said and basically the text in the drop area is a seperate widget and it's state can't be updated whenever we move files into the window to drop. 
And also look into the thing about the flutter format test, if it fails again I will update the workflows folder and check if the same error is given or not.

**Comment by Techno-Disaster** [comment]
> Heyy, @Techno-Disaster , I've tried to do what you said and basically the text in the drop area is a seperate widget and it's state can't be updated whenever we move files into the window to drop. And also look into the thing about the flutter format test, if it fails again I will update the workflows folder and check if the same error is given or not.

Why not? maybe you can try listening to `onDragEntered` and `onDragExited` to update that state? lift up a variable?

**Comment by manoj1749** [comment]
> > Heyy, @Techno-Disaster , I've tried to do what you said and basically the text in the drop area is a seperate widget and it's state can't be updated whenever we move files into the window to drop. And also look into the thing about the flutter format test, if it fails again I will update the workflows folder and check if the same error is given or not.
> 
> 
> 
> Why not? maybe you can try listening to `onDragEntered` and `onDragExited` to update that state? lift up a variable? The formatting workflow is correct, just run the required commands https://github.com/CCExtractor/ccextractorfluttergui/pull/37#issuecomment-1029350543

Ohk, Thanks for suggesting it, I will work on it and update you soon

**Comment by manoj1749** [comment]
- Now Dashboard updates its state everytime based on the `onDragEntered` and `onDragExited`  as the user interacts with the files on the dashboard as shown in the video below

https://user-images.githubusercontent.com/83648898/218220564-fc9c8010-129d-493d-b764-52dfc7beddce.mp4

**Comment by manoj1749** [comment]
- Heyy @Techno-Disaster `flutter test` is running fine without errors 

Xnip2023-02-11_19-54-58

- should I need to test it in windows?

**Comment by Techno-Disaster** [comment]
Strange, they should work in the ci too. Looks like something is wrong with bloc_test.dart? Can you confirm if it works on flutter 3.7.3?

**Comment by manoj1749** [comment]
> Strange, they should work in the ci too. Looks like something is wrong with bloc_test.dart? Can you confirm if it works on flutter 3.7.3?

You mean the flutter version I am using or the version of the environment I declared in the pubsec file?

**Comment by Techno-Disaster** [comment]
> 

yep, if yes maybe look into why ci tests are failing too :D

**Comment by manoj1749** [comment]
> > 
> 
> yep, if yes maybe look into why ci tests are failing too :D

The version I had is 3.3.9, I had tried googling about the error but what I can find is problem with the bloc_test.dart
but I am not able to figure out what is wrong in it, can you help me out?

**Comment by Techno-Disaster** [comment]
> 

Try upgrading to 3.7.3, the bloc test probably shows some analyzer warnings and breaks locally then too.

**Comment by manoj1749** [comment]
> > 
> 
> Try upgrading to 3.7.3, the bloc test probably shows some analyzer warnings and breaks locally then too.

Yeah I had upgraded to 3.7.3, it's showing an error same as the one which we are getting in the CI tests

**Comment by manoj1749** [comment]
As from what I had seen, the error is due to the package called file, as you can see it from the error
```
./../../.pub-cache/hosted/pub.dev/file-6.1.0/lib/src/forwarding/forwarding_file.dart:18:16: Error: The
method 'ForwardingFile.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false}) async =>
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method
('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../.pub-cache/hosted/pub.dev/file-6.1.0/lib/src/forwarding/forwarding_file.dart:18:16: Error: The
method 'ForwardingFile.create' doesn't have the named parameter 'exclusive' of overridden method
'File.create'.
  Future<File> create({bool recursive = false}) async =>
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method
('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../.pub-cache/hosted/pub.dev/file-6.1.0/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method
'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method
('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../../.pub-cache/hosted/pub.dev/file-6.1.0/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method
'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method
'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method
('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
```

**Comment by manoj1749** [comment]
Solved the issues, ci tests are not failing

**Comment by Techno-Disaster** [comment]
LGTM, nice work!

**Comment by manoj1749** [comment]
Thanks😁

**Pull request merged**
