### PR TITLE
Updated Files and Documents

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
### Minor updates with easy merging and no feature changes.

Fixes  issue #15 

- Updated pubspeck.lock and dependencies with the introduction of Flutter 2.8!
- Added punctuation marks and fixed typos in documentation.
- Added Podfile and other iOS files generated while running in the iOS environment.

### CODE REVIEW

**Comment by ItsAdityaKSingh** [comment]
@Techno-Disaster, my local tests are passing; any idea why CI tests fail? I guess it's because CI tests use flutter 2.8 to build and test. Could you look into it?

**Comment by Techno-Disaster** [comment]
> 

The ci uses flutter master (which should probably be changed) , didn't you use flutter to 2.8 in this PR as well?

**Comment by ItsAdityaKSingh** [comment]
Yeah, I did, that's the reason for updates in pubspeck.lock file.

**Comment by Techno-Disaster** [comment]
> Yeah, I did, that's the reason for updates in pubspeck.lock file.

does flutter test work for you locally? if not you should probably fix that.

**Comment by ItsAdityaKSingh** [comment]
Sure I am going to give it a look, seems like I'm having some errors running it now.

**Pull request closed without merging**
